version: '3.8'

services:

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  # products-db:
  #   image: mongo:latest
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27028:27017
  #   volumes:
  #     - products-data:/data/db

  users-api:
    build: ./api/accounts-sub-api
    restart: always
    ports:
      - 7700:7700
    depends_on:
      - db
    # networks:
    #   - api-network

  products-api:
    build: ./api/products-sub-api
    restart: always
    ports:
      - 7555:7555
    depends_on:
      - db
    # networks:
    #   - api-network

  master-api:
    build: ./api/master-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - users-api
      - products-api
    # networks:
    #   - api-network
#  website:
#    build: cloud_website/.
#    ports:
#      - 4444:80
#    depends_on:
#      - api
#    links:
#      - api
# networks:
#   api-network:
#     driver: bridge

volumes:
  data: